# Generated by Django 4.2.7 on 2023-11-25 04:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_empresa_people_equipe_avaliador"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="avaliador",
            options={"verbose_name_plural": "Avaliadores"},
        ),
    ]
